### ISSUE TITLE
Collider

### ISSUE THREAD

**Issue by Lc-Njamen** [Lc-Njamen/Flight-Simulator#4]
GameObject with colliders can not rotate

**Comment by Betarabbit14** [comment]
Is there a specific error code that pops up while trying to rotate?

**Comment by Lc-Njamen** [comment]
nothing, maybe this but I think it doesn't matter right ?
: Invalid editor window UnityEditor.FallbackEditorWindow
UnityEditor.EditorApplicationLayout:FinalizePlaymodeLayout()

**Comment by Betarabbit14** [comment]
Yea thats just an editor error nothing wrong with the game

**Comment by Betarabbit14** [comment]
If its fixed please remember to post your solution and close the issue! :)
